version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" = 'circleci-project-setup' ]; then
              aws s3 sync build s3://example-react-app-from-ekpono --delete --exact-timestamps
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup

