version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: /Nike-shoes-website/.circleci  # Use the default home directory for circleci user
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install -i  # Update this to npm install if needed
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id $AKIAXUEBMHW2GRLNTOU2
            aws configure set aws_secret_access_key $azIewsAwjHr7E/eq2D8WZ4cKzPeF5cGzyATacbpr
            aws s3 sync dist/ s3://s3-worrior --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
